apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: ef-lifeline
  namespace: lifeline
spec:
  workloadSelector:
    labels:
      tenantid: lifeline
  filters:
  - listenerMatch:
      portNumber: 80
      listenerType: SIDECAR_OUTBOUND
      listenerProtocol: HTTP
    filterName: envoy.lua
    filterType: HTTP
    filterConfig:
      inlineCode: |
        function envoy_on_request(request_handle)
          request_handle:logInfo("******* enter envoy_on_request ef-lifeline")
          request_handle:headers():replace("tenant_id2","lifeline")
        end 
